add fabric modify road map as far as I can remember
Hyperledger-TWGC/fabric-gm-wiki pull request #14
Opened 2021-01-29 16:27 UTC by SamYuan1990

Resolve for #13 

Signed-off-by: SamYuan1990 <yy19902439@126.com>

2021-01-29 16:31 UTC, guoger reviewed
LGTM, 不过希望有其他人review

2021-01-31 06:43 UTC, davidkhala commented on GMFabricRoadMap.md
> +golang开发库：
这一段是什么？

2021-01-31 06:44 UTC, davidkhala requested changes
golang开发库那一段含义不明

2021-01-31 07:03 UTC, SamYuan1990 commented on GMFabricRoadMap.md
> +golang开发库：
知识背景，比如概念和具体需要了解的golang库。
免的有人说不知道怎么动手做。

2021-01-31 07:17 UTC, davidkhala commented on GMFabricRoadMap.md
> +golang开发库：
理解这个用意，我的意思是即使是我也看不太懂这里具体是指的什么，会不会做成带链接的文字更好一点

2021-01-31 07:20 UTC, SamYuan1990 commented on GMFabricRoadMap.md
> +golang开发库：
好提议。那我就把这些库尽可能的加上到golang doc链接。

2021-01-31 07:31 UTC, SamYuan1990 commented on GMFabricRoadMap.md
> +golang开发库：
updated.

2021-01-31 08:16 UTC, SamYuan1990 commented
> golang开发库那一段含义不明

已经添加了对应golang库的链接。

2021-02-01 05:58 UTC, davidkhala approved these changes
LGTM
@guijunchen 桂军看一眼？

2021-02-01 11:41 UTC, guijunchen reviewed
已添加修改，可以先确定一个初版，有不确定问题，留到周会一起讨论确定下来。

2021-02-01 11:41 UTC, guijunchen commented on GMFabricRoadMap.md
> +    在完成了国密测试集的改造（或者说对测试集进行国密改造）与接口改造工作后。我们就需要进行国密版本的bccsp实现以通过所有的国密测试场景。完成测试驱动开发的过程。
关于需要确定BCCSP  gmsw mode 对接三个不同密码基础库，甚至更多。还要支持pkcs11对应国密标准SDF接口
BCCSP {
         SW:  --> golang crypto
         PKCS11: --> hsm(pkcs11 api)
         GMSW: --> {
                 tjfoc-gm
                 ccs-gm
                 pku-gm
          }
          sdf: -->  hsm(sdf api)
}
这里之前讨论最多是在三个基础库切换问题！

2021-02-01 11:41 UTC, guijunchen commented on GMFabricRoadMap.md
> +## 大方向
现在的大方向是比较理想目标，实施起来比较困难
这里是否分为三个step or  plan 比较好
step or plan 1 :  先进行“硬改”
step or plan 2 : 对“硬改方案进行cli级别测试覆盖”
step or plan 3:   在前面基础上，进行hash下沉修改， 单元测试覆盖， 集成测测试覆盖等等

2021-02-01 11:41 UTC, guijunchen commented on GMFabricRoadMap.md
> +
现在还缺少对SDK改造的说明：
比如java sdk之前讨论改造,是实现自己class替换？

2021-02-01 11:41 UTC, guijunchen commented on GMFabricRoadMap.md
> +### 参考记录
现在也缺少fabric-ca改造说明：
之前讨论Fabric-ca暂时确定以锚定每个版本进行“硬改”方式。

2021-03-20 13:28 UTC, davidkhala commented
@guijunchen 桂军如果ready to review就通知我，现在这几个commit还是缺乏签名

2021-04-20 12:56 UTC, davidkhala commented
@guijunchen 桂军，路线图有进展了么？

2021-04-23 13:15 UTC, closed without merging